from pathlib import Path

service_path = Path("services/velia_conversation_links_bidirectional_service.py")
source = service_path.read_text(encoding="utf-8")

marker = '''\ndef link_conversations_bidirectional(\n'''
helper = '''\ndef _lock_user_conversations_for_link_mutation(cursor, user_id: int) -> Set[str]:\n    \"\"\"Stabilize archive/delete state for every existing edge endpoint.\n\n    Link mutations are infrequent, while a user's chat set is bounded in normal\n    mobile use. Locking all non-deleted conversation rows in deterministic order\n    closes the race where a linked neighbor is archived between stale cleanup and\n    capacity evaluation. Archive/delete updates then either commit before this\n    statement (and are observed) or wait until the link transaction commits.\n    \"\"\"\n\n    cursor.execute(\n        \"\"\"\n        SELECT conversation_id, is_archived\n        FROM velia_conversations\n        WHERE user_id=%s AND deleted_at IS NULL\n        ORDER BY conversation_id ASC\n        FOR UPDATE\n        \"\"\",\n        (int(user_id),),\n    )\n    active_ids: Set[str] = set()\n    for row in cursor.fetchall() or []:\n        conversation_id = str(_row_value(row, \"conversation_id\", 0, \"\"))\n        is_archived = bool(_row_value(row, \"is_archived\", 1, False))\n        if conversation_id and not is_archived:\n            active_ids.add(conversation_id)\n    return active_ids\n\n\n'''
if helper.strip() not in source:
    if marker not in source:
        raise SystemExit("link function marker not found")
    source = source.replace(marker, helper + marker, 1)

old = '''    participant_ids = sorted(set([anchor_id] + peer_ids))\n    placeholders = ",".join(["%s"] * len(participant_ids))\n    conn = get_connection()\n    cursor = legacy._dict_cursor(conn)\n    try:\n        # Every mutation involving a chat locks that stable conversation row first.\n        # This serializes concurrent link operations even when no edge row exists yet.\n        cursor.execute(\n            f\"\"\"\n            SELECT conversation_id, title\n            FROM velia_conversations\n            WHERE user_id=%s\n              AND conversation_id IN ({placeholders})\n              AND deleted_at IS NULL\n              AND is_archived=FALSE\n            ORDER BY conversation_id ASC\n            FOR UPDATE\n            \"\"\",\n            tuple([uid] + participant_ids),\n        )\n        active_ids = {\n            str(_row_value(row, \"conversation_id\", 0, \"\"))\n            for row in cursor.fetchall() or []\n        }\n        if active_ids != set(participant_ids):\n            raise ConversationUxError(\"conversation_not_found\", status=404)\n\n        # Do this inside the same transaction and after locking participant rows.\n        # Otherwise an archived peer could stop counting, a replacement could take\n        # its slot, and the old edge could later resurrect as a fifth active peer.\n        _delete_inactive_edges_touching(cursor, uid, participant_ids)\n'''
new = '''    participant_ids = sorted(set([anchor_id] + peer_ids))\n    conn = get_connection()\n    cursor = legacy._dict_cursor(conn)\n    try:\n        # Stabilize every possible existing edge endpoint before cleanup/counting.\n        # This closes the archive/delete race across separate SQL statements.\n        active_ids = _lock_user_conversations_for_link_mutation(cursor, uid)\n        if not set(participant_ids).issubset(active_ids):\n            raise ConversationUxError(\"conversation_not_found\", status=404)\n\n        _delete_inactive_edges_touching(cursor, uid, participant_ids)\n'''
if old not in source:
    raise SystemExit("expected participant-lock block not found")
source = source.replace(old, new, 1)
service_path.write_text(source, encoding="utf-8")

test_path = Path("tests/test_velia_bidirectional_chat_links.py")
tests = test_path.read_text(encoding="utf-8")
insert_before = '''\ndef test_legacy_fan_in_is_not_truncated_to_new_link_limit():\n'''
new_test = '''\ndef test_link_mutation_locks_user_conversations_before_cleanup_and_capacity():\n    class RecordingCursor:\n        def __init__(self):\n            self.calls = []\n\n        def execute(self, query, params=None):\n            self.calls.append((\" \".join(str(query).split()), tuple(params or ())))\n\n        def fetchall(self):\n            return [\n                {\"conversation_id\": \"chat-a\", \"is_archived\": False},\n                {\"conversation_id\": \"chat-b\", \"is_archived\": False},\n                {\"conversation_id\": \"chat-old\", \"is_archived\": True},\n            ]\n\n    cursor = RecordingCursor()\n    active = service._lock_user_conversations_for_link_mutation(cursor, 17)\n\n    assert active == {\"chat-a\", \"chat-b\"}\n    query, params = cursor.calls[0]\n    assert \"FROM velia_conversations\" in query\n    assert \"WHERE user_id=%s AND deleted_at IS NULL\" in query\n    assert \"ORDER BY conversation_id ASC FOR UPDATE\" in query\n    assert params == (17,)\n\n    source = Path(\"services/velia_conversation_links_bidirectional_service.py\").read_text(encoding=\"utf-8\")\n    lock_call = \"active_ids = _lock_user_conversations_for_link_mutation(cursor, uid)\"\n    cleanup_call = \"_delete_inactive_edges_touching(cursor, uid, participant_ids)\"\n    active_edge_call = \"edges = _active_edges(cursor, uid)\"\n    assert source.index(lock_call) < source.index(cleanup_call) < source.index(active_edge_call)\n\n\n'''
if "test_link_mutation_locks_user_conversations_before_cleanup_and_capacity" not in tests:
    if insert_before not in tests:
        raise SystemExit("test insertion marker not found")
    tests = tests.replace(insert_before, new_test + insert_before, 1)
    test_path.write_text(tests, encoding="utf-8")
