[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:webapp]
command=python run_web_process.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:api-worker]
command=python run_api_worker.py
directory=/app
autostart=true
autorestart=true
startsecs=10
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:opportunity-worker]
command=python run_opportunity_worker.py
directory=/app
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:webhook-worker]
command=python run_webhook_worker.py
directory=/app
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:velia-memory-shadow-worker]
command=python run_velia_memory_shadow_worker.py
directory=/app
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:commercial-worker]
command=python run_api_commercial_worker.py
directory=/app
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:bot]
command=python run_bot_process.py
directory=/app
autostart=true
autorestart=true
startsecs=35
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
