def get_analysis_guide(lang: str = "ru") -> str:
    if lang == "ru":
        return (
            "📘 Как читать анализ DeepAlpha\n"
            "────────────────\n\n"
            "📊 Decision:\n"
            "NO TRADE — нет преимущества\n"
            "WAIT — ждать подтверждения\n"
            "TRADE — есть возможность входа\n\n"
            "💣 Mispricing:\n"
            "Δ < 5% — нет альфы\n"
            "5–20% — умеренная альфа\n"
            "20%+ — сильная, но риск\n\n"
            "📈 Time Shift:\n"
            "Показывает как меняется вероятность со временем\n\n"
            "📡 Trigger Watch:\n"
            "🔴 High — сильное влияние\n"
            "🟡 Medium — среднее\n"
            "🟢 Low — шум\n\n"
            "🧠 Market Psychology:\n"
            "Показывает настроение рынка\n\n"
            "🟡 Alpha Note:\n"
            "Есть ли реальное преимущество\n\n"
            "📊 Trade Insight:\n"
            "Что делать сейчас\n\n"
        )
    else:
        return (
            "📘 How to read DeepAlpha analysis\n"
            "────────────────\n\n"
            "📊 Decision:\n"
            "NO TRADE — no edge\n"
            "WAIT — wait for confirmation\n"
            "TRADE — potential opportunity\n\n"
            "💣 Mispricing:\n"
            "Δ < 5% — no alpha\n"
            "5–20% — moderate alpha\n"
            "20%+ — strong but risky\n\n"
            "📈 Time Shift:\n"
            "Shows how probability changes over time\n\n"
            "📡 Trigger Watch:\n"
            "🔴 High — strong impact\n"
            "🟡 Medium — moderate\n"
            "🟢 Low — noise\n\n"
            "🧠 Market Psychology:\n"
            "Shows market sentiment\n\n"
            "🟡 Alpha Note:\n"
            "Indicates if real edge exists\n\n"
            "📊 Trade Insight:\n"
            "What to do now\n\n"
        )
