"""Render the existing production/medical recipes with mandatory CI stages."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def named_recipe(path, stage):
    lines = (ROOT / path).read_text().splitlines()
    if sum(line.startswith('FROM ') for line in lines) != 1:
        raise RuntimeError(f'Review multi-stage recipe before composing: {path}')
    lines[0] += ' AS ' + stage
    return '\n'.join(lines) + '\n'


def render():
    medical = named_recipe('medical_worker/Dockerfile', 'medical-verified')
    production = named_recipe('Dockerfile', 'production')
    return '''# Generated by ci/render-verified-dockerfile.py; edit its inputs.
''' + medical + '''
COPY . /app
ARG RAILWAY_GIT_COMMIT_SHA
RUN python /app/ci/railway-verified-ci.py medical-image --commit "$RAILWAY_GIT_COMMIT_SHA"

FROM postgres:16-bookworm AS validation-base
RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-venv nodejs \\
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

FROM validation-base AS backend-verified
COPY requirements.txt /app/requirements.txt
COPY medical_worker/requirements.txt /app/medical_worker/requirements.txt
COPY vendor/aiogram_compat /app/vendor/aiogram_compat
RUN python3 -m venv /opt/tests \\
    && /opt/tests/bin/pip install --no-cache-dir -r requirements.txt -r medical_worker/requirements.txt pytest pytest-asyncio PyYAML==6.0.2
COPY --chown=postgres:postgres . /app
RUN mkdir -p /opt/velia-ci && chown postgres:postgres /opt/velia-ci
USER postgres
ARG RAILWAY_GIT_COMMIT_SHA
RUN /opt/tests/bin/python ci/railway-verified-ci.py backend --commit "$RAILWAY_GIT_COMMIT_SHA"

FROM validation-base AS flash-verified
COPY --from=python:3.12-bookworm /usr/local /usr/local
RUN /usr/local/bin/python3.12 -m venv /opt/tests \\
    && /opt/tests/bin/pip install --no-cache-dir pytest requests psycopg2-binary python-dotenv aiohttp tonsdk cryptography pillow pypdf python-multipart PyYAML==6.0.2
COPY --chown=postgres:postgres . /app
RUN mkdir -p /opt/velia-ci && chown postgres:postgres /opt/velia-ci
USER postgres
ARG RAILWAY_GIT_COMMIT_SHA
RUN /opt/tests/bin/python ci/railway-verified-ci.py flash --commit "$RAILWAY_GIT_COMMIT_SHA"

''' + production + '''
# These copies force every validation stage to succeed before producing an image.
COPY --from=backend-verified /opt/velia-ci/backend.json /opt/velia-ci/backend.json
COPY --from=flash-verified /opt/velia-ci/flash.json /opt/velia-ci/flash.json
COPY --from=medical-verified /opt/velia-ci/medical-image.json /opt/velia-ci/medical-image.json
ARG RAILWAY_GIT_COMMIT_SHA
RUN python ci/railway-verified-ci.py verify --commit "$RAILWAY_GIT_COMMIT_SHA"
'''


if __name__ == '__main__':
    path = ROOT / 'ci/Dockerfile.verified-backend'
    expected = render()
    if '--check' in sys.argv:
        if path.read_text() != expected:
            raise SystemExit('Verified Dockerfile is stale; run ci/render-verified-dockerfile.py')
    else:
        path.write_text(expected)
